POST https://proyectos3.sertor.es/api/v1/auth/signup
Content-Type: application/json

{
  "correo": "adrian.toral@live.u-tad.com",
  "nombre_completo": "Adrian Toral",
  "alias": "adriantoral1",
  "password": "12345",
  "frase_recuperacion": "adriantoral"
}

###

POST https://proyectos3.sertor.es/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "adrian.toral@live.u-tad.com",
  "password": "12345"
}

###

GET https://proyectos3.sertor.es/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzA5NDc3OTg2LCJleHAiOjE3MDk1NjQzODZ9.sMNJu1ZwNXDmwsm2C44CYK95Sj6NK6xIgR_hXULJruU