import {Inter} from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';

import NavBar from "@/components/NavBar";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="d-flex flex-column vh-100 p-0 m-0">
            <NavBar/>
            {children}
        </div>
        </body>
        </html>
    )
}
