# correo, nombre_completo, alias, password, descripcion, portfolio, foto, rol, promocion, codigo
POST https://api.reservorio-u-tad.com/api/v1/auth/signup
Content-Type: application/json

{
  "correo": "oscar.simon@live.u-tad.com",
  "nombre_completo": "Oscar Simon",
  "alias": "oscar.s",
  "password": "@Oscar12345",
  "descripcion": "Estudiante de U-Tad",
  "portfolio": "portfolio",
  "foto": "foto",
  "rol": "alumno",
  "promocion": 2025
}

###

POST https://api.reservorio-u-tad.com/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "adrian.toral@live.u-tad.com",
  "password": "Adriantoral@12345"
}

###

POST https://api.reservorio-u-tad.com/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "oscar.simon@live.u-tad.com",
  "password": "@Oscar12345"
}

###

GET https://api.reservorio-u-tad.com/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiY29ycmVvIjoib3NjYXIudml1ZGV6QGxpdmUudS10YWQuY29tIiwiaWF0IjoxNzEzOTEyNDAyLCJleHAiOjE3MTM5OTg4MDJ9.QIOwxKd8RWxmAqOPH-oWKazH5mWPSZ_eKJvsemLT5lY

###

GET https://api.reservorio-u-tad.com/api/v1/proyectos/pendientes?page=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiYWRyaWFuLnRvcmFsQGxpdmUudS10YWQuY29tIiwiaWF0IjoxNzE1MjkwNjY5LCJleHAiOjE3MTUzNzcwNjl9.OmeGVwYbaYdC02dlfPGViRf_nk2a-J5n8tuoX_kEswY

###

GET https://api.reservorio-u-tad.com/api/v1/proyectos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiYWRyaWFuLnRvcmFsQGxpdmUudS10YWQuY29tIiwiaWF0IjoxNzE1MjkwNjY5LCJleHAiOjE3MTUzNzcwNjl9.OmeGVwYbaYdC02dlfPGViRf_nk2a-J5n8tuoX_kEswY

###

GET https://api.reservorio-u-tad.com/api/v1/proyectos/7/aceptar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiYWRyaWFuLnRvcmFsQGxpdmUudS10YWQuY29tIiwiaWF0IjoxNzE1MTA0NDczLCJleHAiOjE3MTUxOTA4NzN9.A5ZEy01HpggJCzc2kp_X_8iqrdeLp01d7aJZxB6Eed0

###

GET https://api.reservorio-u-tad.com/api/v1/auth/signup/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYWNoZV9rZXkiOiJwZW5kaW5nOm9zY2FyLnZpdWRlekBsaXZlLnUtdGFkLmNvbSIsImlhdCI6MTcxMDYzMDM4MSwiZXhwIjoxNzEwNjMyMTgxfQ.YGXrSZIjLR0jfFzwYD7qtWRt2sAEu6em2nOIuF0p9JE

###

DELETE https://api.reservorio-u-tad.com/api/v1/proyectos/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiYWRyaWFuLnRvcmFsQGxpdmUudS10YWQuY29tIiwiaWF0IjoxNzE1MTA0NDczLCJleHAiOjE3MTUxOTA4NzN9.A5ZEy01HpggJCzc2kp_X_8iqrdeLp01d7aJZxB6Eed0

###

GET https://api.reservorio-u-tad.com/api/v1/asignaturas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoib3NjYXIudml1ZGV6QGxpdmUudS10YWQuY29tIiwicm9sIjoiY29vcmRpbmFkb3IiLCJpYXQiOjE3MTE0NjczOTQsImV4cCI6MTcxMTU1Mzc5NH0.699v4mayndc5nSeGT3hhybtOk_Ucs5c3Q7i31Zl7YaA

###