# correo, nombre_completo, alias, password, descripcion, portfolio, foto, rol, promocion, codigo
POST https://api.reservorio-u-tad.com/api/v1/auth/signup
Content-Type: application/json

{
  "correo": "oscar.viudez@live.u-tad.com",
  "nombre_completo": "Oscar Viudez",
  "alias": "oscar.viudez",
  "password": "Oscar@12345",
  "descripcion": "Estudiante de U-Tad",
  "portfolio": "portfolio",
  "foto": "foto",
  "rol": "coordinador",
  "promocion": 2025
}

###

POST https://api.reservorio-u-tad.com/api/v1/auth/signin
Content-Type: application/json

{
  "correo": "oscar.viudez@live.u-tad.com",
  "password": "Oscar@12345"
}

###

GET https://api.reservorio-u-tad.com/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjoiY29vcmRpbmFkb3IiLCJpYXQiOjE3MTAzNTE5NzMsImV4cCI6MTcxMDQzODM3M30.ppUCX18l3a6NFnym0SK4i0kaniu3eeo-M6V-cISfND4

###

GET https://api.reservorio-u-tad.com/api/v1/proyectos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoib3NjYXIudml1ZGV6QGxpdmUudS10YWQuY29tIiwicm9sIjoiY29vcmRpbmFkb3IiLCJpYXQiOjE3MTE0NjczOTQsImV4cCI6MTcxMTU1Mzc5NH0.699v4mayndc5nSeGT3hhybtOk_Ucs5c3Q7i31Zl7YaA

###

GET https://api.reservorio-u-tad.com/api/v1/proyectos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoib3NjYXIudml1ZGV6QGxpdmUudS10YWQuY29tIiwicm9sIjoiY29vcmRpbmFkb3IiLCJpYXQiOjE3MTA2MzA3NTQsImV4cCI6MTcxMDcxNzE1NH0.mV3xcIvmlk9QhIJkIn8AZSc6-Jettv4Reroz0of_1FI

###

GET https://api.reservorio-u-tad.com/api/v1/proyectos/1/aceptar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoib3NjYXIudml1ZGV6QGxpdmUudS10YWQuY29tIiwicm9sIjoiY29vcmRpbmFkb3IiLCJpYXQiOjE3MTE0Njk3ODIsImV4cCI6MTcxMTU1NjE4Mn0.mrdf-gG1LydZYZyVKxUX3oqgULZowxwmGBdkPu00oKc

###

GET https://api.reservorio-u-tad.com/api/v1/auth/signup/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYWNoZV9rZXkiOiJwZW5kaW5nOm9zY2FyLnZpdWRlekBsaXZlLnUtdGFkLmNvbSIsImlhdCI6MTcxMDYzMDM4MSwiZXhwIjoxNzEwNjMyMTgxfQ.YGXrSZIjLR0jfFzwYD7qtWRt2sAEu6em2nOIuF0p9JE

###

DELETE https://api.reservorio-u-tad.com/api/v1/proyectos/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoib3NjYXIudml1ZGV6QGxpdmUudS10YWQuY29tIiwicm9sIjoiY29vcmRpbmFkb3IiLCJpYXQiOjE3MTA3ODUwMjEsImV4cCI6MTcxMDg3MTQyMX0.YwyKyJ2pWo8cuuY9UoRXAIELTDtza8dXZCRfuFtxAgU

###

GET https://api.reservorio-u-tad.com/api/v1/asignaturas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoib3NjYXIudml1ZGV6QGxpdmUudS10YWQuY29tIiwicm9sIjoiY29vcmRpbmFkb3IiLCJpYXQiOjE3MTE0NjczOTQsImV4cCI6MTcxMTU1Mzc5NH0.699v4mayndc5nSeGT3hhybtOk_Ucs5c3Q7i31Zl7YaA

###